-- Auto-generated by scripts/generate-orcid-import-sql.mjs
-- Source: orcid_turath_researchers.csv (71 rows with @uoturath.edu.iq email)
-- Inserts:  71 researchers
-- ORCID links: 71
-- Skipped: 0  (none)
--
-- Run via Supabase Studio → SQL Editor. Idempotent — safe to re-run.

BEGIN;

INSERT INTO public.researchers (username, full_name_en, full_name_ar, private_email, is_public)
VALUES
  ('sabah-majeed', 'Sabah Alnajjar', 'Sabah Alnajjar', 'sabah.majeed@uoturath.edu.iq', true),
  ('ali-husham', 'Ali Husham', 'Ali Husham', 'ali.husham@uoturath.edu.iq', true),
  ('maryam-saleem', 'Maryam Alshakarchy', 'Maryam Alshakarchy', 'maryam.saleem@uoturath.edu.iq', true),
  ('suzan-wadie', 'Susan Sarsam', 'Susan Sarsam', 'suzan.wadie@uoturath.edu.iq', true),
  ('mustafa-ali', 'Mustafa Ali Hadi', 'Mustafa Ali Hadi', 'mustafa.ali@uoturath.edu.iq', true),
  ('rahif-naser', 'Rahif Naser', 'Rahif Naser', 'rahif.naser@uoturath.edu.iq', true),
  ('eman-abdulrezaq', 'Eman Alayash', 'Eman Alayash', 'eman.abdulrezaq@uoturath.edu.iq', true),
  ('qais-abass', 'Qais Abbas', 'Qais Abbas', 'qais.abass@uoturath.edu.iq', true),
  ('afyaa-latif', 'Afeiaa Lateef Jasim', 'Afeiaa Lateef Jasim', 'afyaa.latif@uoturath.edu.iq', true),
  ('yousif-kadhim', 'Yousif Al-haidary', 'Yousif Al-haidary', 'yousif.kadhim@uoturath.edu.iq', true),
  ('alaa-abdulhamid', 'علاء عبدالحميد عبدالله', 'علاء عبدالحميد عبدالله', 'alaa.abdulhamid@uoturath.edu.iq', true),
  ('thuraya-amer', 'Thuraya Amer', 'Thuraya Amer', 'thuraya.amer@uoturath.edu.iq', true),
  ('roaa-hamed', 'Rowaa Sadii', 'Rowaa Sadii', 'roaa.hamed@uoturath.edu.iq', true),
  ('mustafa-zayer', 'Mustafa Zayer', 'Mustafa Zayer', 'mustafa.zayer@uoturath.edu.iq', true),
  ('sajidah-hussein', 'Sajidah Hussein', 'Sajidah Hussein', 'sajidah.hussein@uoturath.edu.iq', true),
  ('asmaa-mahdi', 'Asmaa Hussein', 'Asmaa Hussein', 'asmaa.mahdi@uoturath.edu.iq', true),
  ('salah-mahdi', 'Salah Mahdi', 'Salah Mahdi', 'salah.mahdi@uoturath.edu.iq', true),
  ('hala-hamid', 'Halla Hameed', 'Halla Hameed', 'hala.hamid@uoturath.edu.iq', true),
  ('humam-mohammed', 'Humam Al Ani', 'Humam Al Ani', 'humam.mohammed@uoturath.edu.iq', true),
  ('mohammed-jasim', 'Mohammed Al-obaidi', 'Mohammed Al-obaidi', 'mohammed.jasim@uoturath.edu.iq', true),
  ('bushra-khairalla', 'Bushra Khanjar', 'Bushra Khanjar', 'bushra.khairalla@uoturath.edu.iq', true),
  ('afif-othman', 'Afif Othman', 'Afif Othman', 'afif.othman@uoturath.edu.iq', true),
  ('abduljabbar-abbas', 'Abdul-jabbar Abbas Oudh', 'Abdul-jabbar Abbas Oudh', 'abduljabbar.abbas@uoturath.edu.iq', true),
  ('isam-shakir', 'Isam Shakir Hamza', 'Isam Shakir Hamza', 'isam.shakir@uoturath.edu.iq', true),
  ('mohammed-fawzi', 'محمد فوزي فيصل .', 'محمد فوزي فيصل .', 'mohammed.fawzi@uoturath.edu.iq', true),
  ('mohammed-a', 'Mohammed Anwar', 'Mohammed Anwar', 'mohammed.a@uoturath.edu.iq', true),
  ('yousuf-kadory', 'Yousif Al-jubori', 'Yousif Al-jubori', 'yousuf.kadory@uoturath.edu.iq', true),
  ('hasain-ali', 'Hasan Ali', 'Hasan Ali', 'hasain.ali@uoturath.edu.iq', true),
  ('fadel', 'Fadhil Madlool Al Kaabi', 'Fadhil Madlool Al Kaabi', 'fadel@uoturath.edu.iq', true),
  ('entidhar-jasim', 'Entidhar J. Al-akkam', 'Entidhar J. Al-akkam', 'entidhar.jasim@uoturath.edu.iq', true),
  ('abdulsattar-awad', 'Abdulsattar Awad Ibrahim', 'Abdulsattar Awad Ibrahim', 'abdulsattar.awad@uoturath.edu.iq', true),
  ('hanan-hadi', 'Hanan Hadi Sahib Al-anssari', 'Hanan Hadi Sahib Al-anssari', 'hanan.hadi@uoturath.edu.iq', true),
  ('sura-sabah', 'Sura Sabah', 'Sura Sabah', 'sura.sabah@uoturath.edu.iq', true),
  ('saad-jader', 'Saad Jaber Al Uqaily', 'Saad Jaber Al Uqaily', 'saad.jader@uoturath.edu.iq', true),
  ('zainab-taha', 'Zainab Jaddoa', 'Zainab Jaddoa', 'zainab.taha@uoturath.edu.iq', true),
  ('noor-mansour', 'Noor Alazawi', 'Noor Alazawi', 'noor.mansour@uoturath.edu.iq', true),
  ('loma-essa', 'Luma Hammodi', 'Luma Hammodi', 'loma.essa@uoturath.edu.iq', true),
  ('mohammed-alhiti', 'Mohammed Mustafa Mohammed Ameen', 'Mohammed Mustafa Mohammed Ameen', 'mohammed.alhiti@uoturath.edu.iq', true),
  ('raafat-ali', 'Raafat Ali Bashar Al-taghlubee', 'Raafat Ali Bashar Al-taghlubee', 'raafat.ali@uoturath.edu.iq', true),
  ('ahlam-qasir', 'Ahlam J. Qassir', 'Ahlam J. Qassir', 'ahlam.qasir@uoturath.edu.iq', true),
  ('taif-mahde', 'Taif Mahdi', 'Taif Mahdi', 'taif.mahde@uoturath.edu.iq', true),
  ('qais-latif', 'Qais Lateef', 'Qais Lateef', 'qais.latif@uoturath.edu.iq', true),
  ('yousif-hassan', 'Yousif Hassan', 'Yousif Hassan', 'yousif.hassan@uoturath.edu.iq', true),
  ('abdulmonam-yaheya', 'Abdulmoam Yaheya Jawad', 'Abdulmoam Yaheya Jawad', 'abdulmonam.yaheya@uoturath.edu.iq', true),
  ('othman-farooq', 'Othman F.b. Al-sawaf', 'Othman F.b. Al-sawaf', 'othman.farooq@uoturath.edu.iq', true),
  ('hala-saadi', 'Hala Abdulwahid', 'Hala Abdulwahid', 'hala.saadi@uoturath.edu.iq', true),
  ('bakr-imad-najm', 'Bakr Alazzawi', 'Bakr Alazzawi', 'bakr.imad.najm@uoturath.edu.iq', true),
  ('laith-sabaa', 'Laith Ismail', 'Laith Ismail', 'laith.sabaa@uoturath.edu.iq', true),
  ('maryam-alihussein', 'Maryam Ali', 'Maryam Ali', 'maryam.alihussein@uoturath.edu.iq', true),
  ('saeed-miran', 'Saeed Miran', 'Saeed Miran', 'saeed.miran@uoturath.edu.iq', true),
  ('sura-altie', 'Sura Abdulhussein Fadhil Al-taie', 'Sura Abdulhussein Fadhil Al-taie', 'sura.altie@uoturath.edu.iq', true),
  ('mustafa-egla', 'Mustafa Egla', 'Mustafa Egla', 'mustafa.egla@uoturath.edu.iq', true),
  ('hanannagem2007', 'Hanan Nagem Alden Mahmood Al-dulaimi', 'Hanan Nagem Alden Mahmood Al-dulaimi', 'hanannagem2007@uoturath.edu.iq', true),
  ('sanan-thaer', 'Dr. Sanan Thaer', 'Dr. Sanan Thaer', 'sanan.thaer@uoturath.edu.iq', true),
  ('ehan-sabah', 'Ehan Sabah Shukri Askari', 'Ehan Sabah Shukri Askari', 'ehan.sabah@uoturath.edu.iq', true),
  ('huda-mhasan', 'Dr. Huda Mohammad Hasan Ali', 'Dr. Huda Mohammad Hasan Ali', 'huda.mhasan@uoturath.edu.iq', true),
  ('suhad-faisal', 'Suhad Faisal', 'Suhad Faisal', 'suhad.faisal@uoturath.edu.iq', true),
  ('saad-mahdi', 'Saad Mahdi', 'Saad Mahdi', 'saad.mahdi@uoturath.edu.iq', true),
  ('alaa-karim', 'Alaa Alkhazraji', 'Alaa Alkhazraji', 'alaa.karim@uoturath.edu.iq', true),
  ('tagreed-fadil', 'Taghreed F. Zaidan', 'Taghreed F. Zaidan', 'tagreed.fadil@uoturath.edu.iq', true),
  ('jaefar-abu-talib', 'Jafar Abu Talib', 'Jafar Abu Talib', 'jaefar.abu.talib@uoturath.edu.iq', true),
  ('maha-sami', 'Maha Barakat', 'Maha Barakat', 'maha.sami@uoturath.edu.iq', true),
  ('louay-a-mahdi', 'Louay Abd Al-azez Mahdi', 'Louay Abd Al-azez Mahdi', 'louay.a.mahdi@uoturath.edu.iq', true),
  ('hasanain-naji', 'Hasanain Altaweel', 'Hasanain Altaweel', 'hasanain.naji@uoturath.edu.iq', true),
  ('kismat-turkikismat', 'Kismat M. Turki', 'Kismat M. Turki', 'kismat.turkikismat@uoturath.edu.iq', true),
  ('ahmed-basher', 'A.b Ayyed', 'A.b Ayyed', 'ahmed.basher@uoturath.edu.iq', true),
  ('hayder-abdulameer', 'Hayder Abdulameer Yousif', 'Hayder Abdulameer Yousif', 'hayder.abdulameer@uoturath.edu.iq', true),
  ('ali-yassen', 'ا.م.د علي ياسين خضير المشهداني', 'ا.م.د علي ياسين خضير المشهداني', 'ali.yassen@uoturath.edu.iq', true),
  ('jamal-manaa', 'Jamal M. Ali', 'Jamal M. Ali', 'jamal.manaa@uoturath.edu.iq', true),
  ('yaserissam-hamodi', 'Yaser Issam Hamodi Al-janabi, Yaser Issam Hamodi And Yaser Issam Hamodi Al-janabi', 'Yaser Issam Hamodi Al-janabi, Yaser Issam Hamodi And Yaser Issam Hamodi Al-janabi', 'yaserissam.hamodi@uoturath.edu.iq', true),
  ('sarah-mouala', 'Sarah Mualla', 'Sarah Mualla', 'sarah.mouala@uoturath.edu.iq', true)
ON CONFLICT (username) DO NOTHING;

-- ORCID social-profile rows. Re-runnable: updates URL if the row exists,
-- inserts otherwise.
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-7530-0344', 'https://orcid.org/0009-0005-7530-0344', true
FROM public.researchers WHERE username = 'sabah-majeed'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-7892-1972', 'https://orcid.org/0000-0002-7892-1972', true
FROM public.researchers WHERE username = 'ali-husham'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0002-8077-127X', 'https://orcid.org/0009-0002-8077-127X', true
FROM public.researchers WHERE username = 'maryam-saleem'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0001-9680-4406', 'https://orcid.org/0000-0001-9680-4406', true
FROM public.researchers WHERE username = 'suzan-wadie'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0002-2402-3891', 'https://orcid.org/0009-0002-2402-3891', true
FROM public.researchers WHERE username = 'mustafa-ali'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0002-3040-9010', 'https://orcid.org/0009-0002-3040-9010', true
FROM public.researchers WHERE username = 'rahif-naser'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-1393-3190', 'https://orcid.org/0009-0000-1393-3190', true
FROM public.researchers WHERE username = 'eman-abdulrezaq'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0006-4240-6078', 'https://orcid.org/0009-0006-4240-6078', true
FROM public.researchers WHERE username = 'qais-abass'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0004-4785-2195', 'https://orcid.org/0009-0004-4785-2195', true
FROM public.researchers WHERE username = 'afyaa-latif'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0007-5233-9582', 'https://orcid.org/0009-0007-5233-9582', true
FROM public.researchers WHERE username = 'yousif-kadhim'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-7164-8546', 'https://orcid.org/0009-0005-7164-8546', true
FROM public.researchers WHERE username = 'alaa-abdulhamid'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-9334-2653', 'https://orcid.org/0000-0002-9334-2653', true
FROM public.researchers WHERE username = 'thuraya-amer'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-3831-2892', 'https://orcid.org/0009-0000-3831-2892', true
FROM public.researchers WHERE username = 'roaa-hamed'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0001-3880-232X', 'https://orcid.org/0009-0001-3880-232X', true
FROM public.researchers WHERE username = 'mustafa-zayer'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0001-8490-8136', 'https://orcid.org/0000-0001-8490-8136', true
FROM public.researchers WHERE username = 'sajidah-hussein'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0006-0299-9438', 'https://orcid.org/0009-0006-0299-9438', true
FROM public.researchers WHERE username = 'asmaa-mahdi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-9990-8524', 'https://orcid.org/0009-0008-9990-8524', true
FROM public.researchers WHERE username = 'salah-mahdi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0006-1419-2471', 'https://orcid.org/0009-0006-1419-2471', true
FROM public.researchers WHERE username = 'hala-hamid'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-2865-9231', 'https://orcid.org/0009-0005-2865-9231', true
FROM public.researchers WHERE username = 'humam-mohammed'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-7369-4272', 'https://orcid.org/0000-0002-7369-4272', true
FROM public.researchers WHERE username = 'mohammed-jasim'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0003-4471-1392', 'https://orcid.org/0000-0003-4471-1392', true
FROM public.researchers WHERE username = 'bushra-khairalla'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-3102-7173', 'https://orcid.org/0009-0008-3102-7173', true
FROM public.researchers WHERE username = 'afif-othman'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0003-5502-5109', 'https://orcid.org/0009-0003-5502-5109', true
FROM public.researchers WHERE username = 'abduljabbar-abbas'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-5162-4522', 'https://orcid.org/0009-0008-5162-4522', true
FROM public.researchers WHERE username = 'isam-shakir'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0007-7264-1738', 'https://orcid.org/0009-0007-7264-1738', true
FROM public.researchers WHERE username = 'mohammed-fawzi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0007-5318-5378', 'https://orcid.org/0009-0007-5318-5378', true
FROM public.researchers WHERE username = 'mohammed-a'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-8390-603X', 'https://orcid.org/0000-0002-8390-603X', true
FROM public.researchers WHERE username = 'yousuf-kadory'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0007-3430-6699', 'https://orcid.org/0009-0007-3430-6699', true
FROM public.researchers WHERE username = 'hasain-ali'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0009-7615-0500', 'https://orcid.org/0009-0009-7615-0500', true
FROM public.researchers WHERE username = 'fadel'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-9359-2053', 'https://orcid.org/0009-0005-9359-2053', true
FROM public.researchers WHERE username = 'entidhar-jasim'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-8966-7093', 'https://orcid.org/0009-0008-8966-7093', true
FROM public.researchers WHERE username = 'abdulsattar-awad'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-7474-4641', 'https://orcid.org/0009-0000-7474-4641', true
FROM public.researchers WHERE username = 'hanan-hadi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0003-2052-8531', 'https://orcid.org/0009-0003-2052-8531', true
FROM public.researchers WHERE username = 'sura-sabah'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-7231-4381', 'https://orcid.org/0009-0000-7231-4381', true
FROM public.researchers WHERE username = 'saad-jader'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0004-9839-5465', 'https://orcid.org/0009-0004-9839-5465', true
FROM public.researchers WHERE username = 'zainab-taha'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-6703-5273', 'https://orcid.org/0009-0000-6703-5273', true
FROM public.researchers WHERE username = 'noor-mansour'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-3096-495X', 'https://orcid.org/0009-0000-3096-495X', true
FROM public.researchers WHERE username = 'loma-essa'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-5974-1352', 'https://orcid.org/0009-0008-5974-1352', true
FROM public.researchers WHERE username = 'mohammed-alhiti'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0002-2237-046X', 'https://orcid.org/0009-0002-2237-046X', true
FROM public.researchers WHERE username = 'raafat-ali'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-0481-9430', 'https://orcid.org/0000-0002-0481-9430', true
FROM public.researchers WHERE username = 'ahlam-qasir'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-0805-7727', 'https://orcid.org/0009-0005-0805-7727', true
FROM public.researchers WHERE username = 'taif-mahde'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0001-8699-682X', 'https://orcid.org/0000-0001-8699-682X', true
FROM public.researchers WHERE username = 'qais-latif'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-1759-0965', 'https://orcid.org/0009-0000-1759-0965', true
FROM public.researchers WHERE username = 'yousif-hassan'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0003-6749-7170', 'https://orcid.org/0009-0003-6749-7170', true
FROM public.researchers WHERE username = 'abdulmonam-yaheya'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0001-1684-9274', 'https://orcid.org/0009-0001-1684-9274', true
FROM public.researchers WHERE username = 'othman-farooq'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0001-5005-8647', 'https://orcid.org/0000-0001-5005-8647', true
FROM public.researchers WHERE username = 'hala-saadi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0001-6430-3751', 'https://orcid.org/0009-0001-6430-3751', true
FROM public.researchers WHERE username = 'bakr-imad-najm'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-8129-3364', 'https://orcid.org/0000-0002-8129-3364', true
FROM public.researchers WHERE username = 'laith-sabaa'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-8494-9719', 'https://orcid.org/0009-0005-8494-9719', true
FROM public.researchers WHERE username = 'maryam-alihussein'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-6197-8906', 'https://orcid.org/0009-0008-6197-8906', true
FROM public.researchers WHERE username = 'saeed-miran'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0003-8319-0320', 'https://orcid.org/0009-0003-8319-0320', true
FROM public.researchers WHERE username = 'sura-altie'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0009-7033-283X', 'https://orcid.org/0009-0009-7033-283X', true
FROM public.researchers WHERE username = 'mustafa-egla'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0003-4241-5258', 'https://orcid.org/0000-0003-4241-5258', true
FROM public.researchers WHERE username = 'hanannagem2007'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-3696-5205', 'https://orcid.org/0000-0002-3696-5205', true
FROM public.researchers WHERE username = 'sanan-thaer'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0006-0995-7775', 'https://orcid.org/0009-0006-0995-7775', true
FROM public.researchers WHERE username = 'ehan-sabah'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0008-6996-9000', 'https://orcid.org/0009-0008-6996-9000', true
FROM public.researchers WHERE username = 'huda-mhasan'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0001-5284-5935', 'https://orcid.org/0000-0001-5284-5935', true
FROM public.researchers WHERE username = 'suhad-faisal'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0003-8449-8706', 'https://orcid.org/0009-0003-8449-8706', true
FROM public.researchers WHERE username = 'saad-mahdi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-5062-6111', 'https://orcid.org/0000-0002-5062-6111', true
FROM public.researchers WHERE username = 'alaa-karim'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-3748-8551', 'https://orcid.org/0000-0002-3748-8551', true
FROM public.researchers WHERE username = 'tagreed-fadil'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0003-3304-1415', 'https://orcid.org/0009-0003-3304-1415', true
FROM public.researchers WHERE username = 'jaefar-abu-talib'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-1172-7131', 'https://orcid.org/0009-0000-1172-7131', true
FROM public.researchers WHERE username = 'maha-sami'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-0577-8714', 'https://orcid.org/0000-0002-0577-8714', true
FROM public.researchers WHERE username = 'louay-a-mahdi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-1858-5735', 'https://orcid.org/0000-0002-1858-5735', true
FROM public.researchers WHERE username = 'hasanain-naji'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-0587-8491', 'https://orcid.org/0000-0002-0587-8491', true
FROM public.researchers WHERE username = 'kismat-turkikismat'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-9614-0343', 'https://orcid.org/0009-0005-9614-0343', true
FROM public.researchers WHERE username = 'ahmed-basher'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0005-8362-0524', 'https://orcid.org/0009-0005-8362-0524', true
FROM public.researchers WHERE username = 'hayder-abdulameer'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0009-0000-6213-4758', 'https://orcid.org/0009-0000-6213-4758', true
FROM public.researchers WHERE username = 'ali-yassen'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-6086-2679', 'https://orcid.org/0000-0002-6086-2679', true
FROM public.researchers WHERE username = 'jamal-manaa'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0003-0135-1665', 'https://orcid.org/0000-0003-0135-1665', true
FROM public.researchers WHERE username = 'yaserissam-hamodi'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();
INSERT INTO public.researcher_social_profiles (researcher_id, platform, username, url, is_verified)
SELECT id, 'orcid', '0000-0002-7276-622X', 'https://orcid.org/0000-0002-7276-622X', true
FROM public.researchers WHERE username = 'sarah-mouala'
ON CONFLICT (researcher_id, platform) DO UPDATE
  SET url = EXCLUDED.url, username = EXCLUDED.username, is_verified = true, updated_at = now();

COMMIT;

-- Verify:
-- SELECT count(*) FROM public.researchers WHERE private_email LIKE '%@uoturath.edu.iq';
-- SELECT count(*) FROM public.researcher_social_profiles WHERE platform = 'orcid';
